### PR TITLE
add pnpm idea

### PR DESCRIPTION
**Pull request by Janik-Haag**

### CODE REVIEW

**Review by Kranzes — CHANGES_REQUESTED** [review]
Add me as a mentor, I need this.

**Comment by Janik-Haag** [comment]
@Kranzes do you think the idea description is fitting, and we can merge this or are you missing anything?

**Comment by Kranzes** [comment]
Looks fine idk, I do know that the tooling in nixpkgs for npm uses python and I considered sharing the code since the npmn and pnpm commands are similar.

**Comment by Janik-Haag** [comment]
huh there is not a single python file in `pkgs/build-support/node/`, the fetcher is rust based and everything else is javascript or nix. You might be able to share some code but most of it esp. relating to git deps will probably have to be redone from the research I did on this.

**Comment by Kranzes** [comment]
oh nvm then, rust, sorry. I got confused with a different fetcher probably.

**Comment by Kranzes** [comment]
I need pnpm for this https://github.com/NixOS/nixpkgs/issues/265653

**Comment by Janik-Haag** [comment]
> I need this.

just keep in mind that the people who are going to work on this (if someone decides to apply for this project) are probably going to be very inexperienced and the focus should be on providing them with a fun learning experience and not on finishing a given project.

**Comment by Kranzes** [comment]
Yeah that's fine

**Pull request merged**
